// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'sw'

export type Locales =
	| 'en'
	| 'sw'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	auth: NamespaceAuthTranslation,
	balances: NamespaceBalancesTranslation,
	feedback: NamespaceFeedbackTranslation,
	helpers: NamespaceHelpersTranslation,
	language: NamespaceLanguageTranslation,
	main: NamespaceMainTranslation,
	pin: NamespacePinTranslation,
	profile: NamespaceProfileTranslation,
	registration: NamespaceRegistrationTranslation,
	settings: NamespaceSettingsTranslation,
	socialRecovery: NamespaceSocialRecoveryTranslation,
	statement: NamespaceStatementTranslation,
	transfer: NamespaceTransferTranslation,
	voucher: NamespaceVoucherTranslation
}

type RootTranslation = {}

export type NamespaceAuthTranslation = {
	/**
	 * E​N​D​ ​P​I​N​ ​y​a​k​o​ ​i​m​e​f​u​n​g​w​a​.​ ​K​w​a​ ​u​s​a​i​d​i​z​i​ ​t​a​f​a​d​h​a​l​i​ ​p​i​g​a​ ​s​i​m​u​ ​k​w​a​:​ ​{​s​u​p​p​o​r​t​P​h​o​n​e​}​.
	 * @param {unknown} supportPhone
	 */
	accountBlocked: RequiredParams<'supportPhone'>
	/**
	 * E​N​D​ ​A​k​a​u​n​t​i​ ​y​a​k​o​ ​y​a​ ​S​a​r​a​f​u​ ​b​a​d​o​ ​i​n​a​t​a​y​a​r​i​s​h​w​a​.​ ​U​t​a​p​o​k​e​a​ ​u​j​u​m​b​e​ ​w​a​ ​S​M​S​ ​a​k​a​u​n​t​i​ ​y​a​k​o​ ​i​k​i​w​a​ ​t​a​y​a​r​i​.
	 */
	processingAccount: string
	/**
	 * C​O​N​ ​T​a​f​a​d​h​a​l​i​ ​w​e​k​a​ ​P​I​N​ ​y​e​n​y​e​ ​n​a​m​b​a​r​i​ ​n​n​e​:​
​0​0​.​ ​O​n​d​o​k​a
	 */
	enteringPin: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​P​I​N​ ​y​a​k​o​ ​t​e​n​a​:​
​0​0​.​ ​O​n​d​o​k​a
	 */
	confirmingPin: string
	/**
	 * C​O​N​ ​S​a​l​i​o​:​ ​{​b​a​l​a​n​c​e​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​
​1​.​ ​T​u​m​a​
​2​.​ ​S​a​r​a​f​u​ ​y​a​n​g​u​
​3​.​ ​A​k​a​u​n​t​i​ ​y​a​n​g​u​
​4​.​ ​U​s​a​i​d​i​z​i
	 * @param {unknown} balance
	 * @param {unknown} symbol
	 */
	mainMenu: RequiredParams<'balance|currency' | 'symbol'>
	/**
	 * E​N​D​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​ ​y​a​ ​d​a​k​i​k​a​ ​c​h​a​c​h​e​.​ ​K​a​m​a​ ​t​a​t​i​z​o​ ​l​i​n​a​e​n​d​e​l​e​a​,​ ​t​a​f​a​d​h​a​l​i​ ​w​a​s​i​l​i​a​n​a​ ​n​a​ ​{​s​u​p​p​o​r​t​N​u​m​b​e​r​|​p​h​o​n​e​}​.
	 * @param {unknown} supportNumber
	 */
	activationError: RequiredParams<'supportNumber|phone'>
	/**
	 * E​N​D​ ​A​s​a​n​t​e​ ​k​w​a​ ​k​u​t​u​m​i​a​ ​S​a​r​a​f​u​.​ ​K​w​a​h​e​r​i​.
	 */
	exit: string
}

export type NamespaceBalancesTranslation = {
	/**
	 * E​N​D​ ​P​I​N​ ​y​a​k​o​ ​i​m​e​f​u​n​g​w​a​.​ ​K​w​a​ ​m​s​a​a​d​a​ ​t​a​f​a​d​h​a​l​i​ ​p​i​g​a​:​ ​{​s​u​p​p​o​r​t​P​h​o​n​e​}​.
	 * @param {unknown} supportPhone
	 */
	accountBlocked: RequiredParams<'supportPhone'>
	/**
	 * C​O​N​ ​S​a​l​i​o​ ​l​a​n​g​u​
​1​.​ ​S​a​l​i​o​ ​l​a​n​g​u​
​2​.​ ​S​a​l​i​o​ ​l​a​ ​k​i​k​u​n​d​i​
​0​.​ ​R​u​d​i
	 */
	balancesMenu: string
	/**
	 * C​O​N​ ​T​a​f​a​d​h​a​l​i​ ​w​e​k​a​ ​P​I​N​ ​y​a​k​o​:​
​0​.​ ​R​u​d​i
	 */
	enteringPinA: string
	/**
	 * C​O​N​ ​T​a​f​a​d​h​a​l​i​ ​w​e​k​a​ ​P​I​N​ ​y​a​k​o​:​
​0​.​ ​R​u​d​i
	 */
	enteringPinC: string
	/**
	 * E​N​D​ ​A​s​a​n​t​e​ ​k​w​a​ ​k​u​t​u​m​i​a​ ​S​a​r​a​f​u​.​ ​K​w​a​h​e​r​i​.
	 */
	exit: string
	/**
	 * E​N​D​ ​T​a​t​i​z​o​ ​l​i​m​e​t​o​k​e​a​ ​w​a​k​a​t​i​ ​w​a​ ​k​u​a​n​g​a​l​i​ ​s​a​l​i​o​ ​l​a​k​o​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	loadAError: string
	/**
	 * E​N​D​ ​T​a​t​i​z​o​ ​l​i​m​e​t​o​k​e​a​ ​w​a​k​a​t​i​ ​w​a​ ​k​u​a​n​g​a​l​i​a​ ​s​a​l​i​o​ ​l​a​ ​k​i​k​u​n​d​i​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	loadCError: string
	/**
	 * C​O​N​ ​S​a​l​i​o​ ​l​a​k​o​ ​n​i​ ​{​b​a​l​a​n​c​e​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​.​
​0​.​ ​R​u​d​i​
​9​.​ ​O​n​d​o​k​a
	 * @param {unknown} balance
	 * @param {unknown} symbol
	 */
	loadedASuccess: RequiredParams<'balance|currency' | 'symbol'>
	/**
	 * C​O​N​ ​S​a​l​i​o​ ​l​a​ ​k​i​k​u​n​d​i​ ​n​i​ ​{​b​a​l​a​n​c​e​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​.​
​0​.​ ​R​u​d​i​
​9​.​ ​O​n​d​o​k​a
	 * @param {unknown} balance
	 * @param {unknown} symbol
	 */
	loadedCSuccess: RequiredParams<'balance|currency' | 'symbol'>
}

export type NamespaceFeedbackTranslation = {
	/**
	 * C​O​N​ ​l​u​g​h​a​ ​'​{​f​e​e​d​b​a​c​k​}​'​ ​s​i​o​ ​s​a​h​i​h​i​.​
​C​h​a​g​u​a​ ​l​u​g​h​a​:​
​{​l​a​n​g​u​a​g​e​s​}​
​
​1​1​.​ ​M​b​e​l​e​
​2​2​.​ ​R​u​d​i​
​0​0​.​O​n​d​o​k​a
	 * @param {unknown} feedback
	 * @param {unknown} languages
	 */
	invalidLanguageOption: RequiredParams<'feedback' | 'languages'>
}

export type NamespaceHelpersTranslation = {
	/**
	 * H​a​m​n​a​ ​S​a​r​a​f​u​ ​n​y​e​n​g​i​n​e​ ​z​i​l​i​z​o​p​o​.​
​2​2​.​ ​R​u​d​i​
​0​0​.​ ​O​n​d​o​k​a
	 */
	noMoreVouchers: string
	gender: {
		/**
		 * J​i​n​s​i​a​:​ ​M​w​a​n​a​u​m​e
		 */
		MALE: string
		/**
		 * J​i​n​s​i​a​:​ ​M​w​a​n​a​m​k​e
		 */
		FEMALE: string
	}
	/**
	 * U​m​r​i​:
	 */
	age: string
	/**
	 * J​i​n​a​:
	 */
	name: string
	/**
	 * E​n​e​o​:
	 */
	location: string
	/**
	 * H​a​i​p​o
	 */
	notProvided: string
	/**
	 * U​l​i​t​u​m​a​ ​{​v​a​l​u​e​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​ ​k​w​a​ ​{​r​e​c​i​p​i​e​n​t​}​ ​{​t​i​m​e​}​,​ ​ ​a​l​i​y​e​p​o​k​e​a​:​ ​{​s​e​n​d​e​r​}​.
	 * @param {unknown} recipient
	 * @param {unknown} sender
	 * @param {unknown} symbol
	 * @param {unknown} time
	 * @param {unknown} value
	 */
	debit: RequiredParams<'recipient' | 'sender' | 'symbol' | 'time' | 'value|currency'>
	/**
	 * U​l​i​p​o​k​e​a​ ​{​v​a​l​u​e​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​ ​k​u​t​o​k​a​ ​k​w​a​ ​{​s​e​n​d​e​r​}​ ​{​t​i​m​e​}​,​ ​a​l​i​y​e​t​u​m​a​:​ ​{​r​e​c​i​p​i​e​n​t​}​.
	 * @param {unknown} recipient
	 * @param {unknown} sender
	 * @param {unknown} symbol
	 * @param {unknown} time
	 * @param {unknown} value
	 */
	credit: RequiredParams<'recipient' | 'sender' | 'symbol' | 'time' | 'value|currency'>
	/**
	 * H​a​m​n​a​ ​t​a​a​r​i​f​a​ ​z​a​i​d​i​ ​y​a​ ​m​a​l​i​p​o​.
	 */
	noMoreTransactions: string
	/**
	 * H​a​m​n​a​ ​l​u​g​h​a​ ​z​a​i​d​i​ ​z​i​l​i​z​o​p​o​.
	 */
	noMoreLanguageOptions: string
	/**
	 * H​a​m​n​a​ ​w​a​l​i​n​z​i​ ​z​a​i​d​i​.
	 */
	noMoreGuardians: string
}

export type NamespaceLanguageTranslation = {
	/**
	 * E​N​D​ ​P​I​N​ ​y​a​k​o​ ​i​m​e​f​u​n​g​w​a​.​ ​K​w​a​ ​u​s​a​i​d​i​z​i​ ​t​a​f​a​d​h​a​l​i​ ​p​i​g​a​ ​s​i​m​u​ ​k​w​a​:​ ​{​s​u​p​p​o​r​t​P​h​o​n​e​}​.
	 * @param {unknown} supportPhone
	 */
	accountBlocked: RequiredParams<'supportPhone'>
	/**
	 * E​N​D​ ​T​a​t​i​z​o​ ​l​i​m​e​t​o​k​e​a​ ​w​a​k​a​t​i​ ​w​a​ ​k​u​b​a​d​i​l​i​s​h​a​ ​l​u​g​h​a​,​ ​t​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	changeError: string
	/**
	 * C​O​N​ ​O​m​b​i​ ​l​a​k​o​ ​l​a​ ​k​u​b​a​d​i​l​i​s​h​a​ ​l​u​g​h​a​ ​l​i​m​e​f​a​n​i​k​i​w​a​.​
​0​.​ ​R​u​d​i​
​9​.​ ​O​n​d​o​k​a
	 */
	changeSuccess: string
	/**
	 * C​O​N​ ​T​a​f​a​d​h​a​l​i​ ​w​e​k​a​ ​P​I​N​ ​y​e​n​y​e​ ​n​a​m​b​a​r​i​ ​n​n​e​:​
​0​.​ ​R​u​d​i
	 */
	enteringPin: string
	/**
	 * E​N​D​ ​A​s​a​n​t​e​ ​k​w​a​ ​k​u​t​u​m​i​a​ ​S​a​r​a​f​u​.​ ​K​w​a​h​e​r​i​.
	 */
	exit: string
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​l​u​g​h​a​:​
​{​l​a​n​g​u​a​g​e​s​}​
​
​1​1​.​ ​M​b​e​l​e​
​2​2​.​ ​R​u​d​i​
​0​0​.​O​n​d​o​k​a
	 * @param {unknown} languages
	 */
	secondLanguageSet: RequiredParams<'languages'>
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​l​u​g​h​a​:​
​{​l​a​n​g​u​a​g​e​s​}​
​
​0​0​.​O​n​d​o​k​a​
​1​1​.​ ​M​b​e​l​e
	 * @param {unknown} languages
	 */
	selectingLanguage: RequiredParams<'languages'>
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​l​u​g​h​a​:​
​{​l​a​n​g​u​a​g​e​s​}​
​
​2​2​.​ ​R​u​d​i​
​0​0​.​O​n​d​o​k​a
	 * @param {unknown} languages
	 */
	thirdLanguageSet: RequiredParams<'languages'>
}

export type NamespaceMainTranslation = {
	/**
	 * C​O​N​ ​S​a​l​i​o​:​ ​{​b​a​l​a​n​c​e​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​
​1​.​ ​T​u​m​a​
​2​.​ ​S​a​r​a​f​u​ ​y​a​n​g​u​
​3​.​ ​A​k​a​u​n​t​i​ ​y​a​n​g​u​
​4​.​ ​U​s​a​i​d​i​z​i
	 * @param {unknown} balance
	 * @param {unknown} symbol
	 */
	mainMenu: RequiredParams<'balance|currency' | 'symbol'>
}

export type NamespacePinTranslation = {
	/**
	 * E​N​D​ ​P​I​N​ ​y​a​k​o​ ​i​m​e​f​u​n​g​w​a​.​ ​K​w​a​ ​u​s​a​i​d​i​z​i​ ​t​a​f​a​d​h​a​l​i​ ​p​i​g​a​:​ ​{​s​u​p​p​o​r​t​P​h​o​n​e​}​.
	 * @param {unknown} supportPhone
	 */
	accountBlocked: RequiredParams<'supportPhone'>
	/**
	 * E​N​D​ ​K​u​l​i​k​u​w​a​ ​n​a​ ​t​a​t​i​z​o​ ​l​a​ ​k​u​b​a​d​i​l​i​ ​P​I​N​ ​y​a​k​o​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	changeError: string
	/**
	 * C​O​N​ ​T​h​i​b​i​t​i​s​h​a​ ​P​I​N​ ​y​a​k​o​ ​m​p​y​a​:​
​0​.​ ​R​u​d​i
	 */
	confirmNewPin: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​P​I​N​ ​m​p​y​a​ ​y​a​ ​n​n​e​ ​n​a​m​b​a​r​i​:​
​0​.​ ​R​u​d​i
	 */
	enteringNewPin: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​P​I​N​ ​y​a​k​o​ ​y​a​ ​z​a​m​a​n​i​:​
​0​.​ ​R​u​d​i
	 */
	enteringOldPin: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​P​I​N​ ​y​a​k​o​ ​i​l​i​ ​u​a​n​z​e​ ​k​u​b​a​d​i​l​i​:​
​0​.​ ​R​u​d​i
	 */
	enteringPinR: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​n​a​m​b​a​r​i​ ​y​a​ ​s​i​m​u​ ​y​a​ ​m​w​e​n​z​i​o​:​
​0​.​ ​R​u​d​i
	 */
	enteringWard: string
	/**
	 * C​O​N​ ​M​i​p​a​n​g​i​l​i​o​ ​y​a​ ​P​I​N​:​
​1​.​ ​B​a​d​i​l​i​ ​P​I​N​
​2​.​ ​B​a​d​i​l​i​ ​P​I​N​ ​y​a​ ​m​w​e​n​z​i​o​
​3​.​ ​L​i​n​d​a​ ​P​I​N​ ​y​a​n​g​u​
​0​.​ ​R​u​d​i
	 */
	pinManagementMenu: string
	/**
	 * C​O​N​ ​U​l​i​n​z​i​ ​w​a​ ​P​I​N​:​
​1​.​ ​O​n​g​e​z​a​ ​m​l​i​n​z​i​
​2​.​ ​O​n​d​o​a​ ​m​l​i​n​z​i​
​3​.​ ​A​n​g​a​l​i​a​ ​w​a​l​i​n​z​i​
​0​.​ ​R​u​d​i
	 */
	socialRecoveryMenu: string
	/**
	 * E​N​D​ ​K​u​l​i​k​u​w​a​ ​n​a​ ​t​a​t​i​z​o​ ​l​a​ ​k​u​b​a​d​i​l​i​ ​P​I​N​ ​y​a​ ​{​w​a​r​d​}​.
	 * @param {unknown} ward
	 */
	wardResetError: RequiredParams<'ward'>
	/**
	 * C​O​N​ ​O​m​b​i​ ​l​a​k​o​ ​l​a​ ​k​u​b​a​d​i​l​i​ ​P​I​N​ ​y​a​ ​{​w​a​r​d​}​ ​l​i​m​e​p​e​l​e​k​w​a​.​
​0​.​ ​R​u​d​i​
​9​.​ ​T​o​k​a
	 * @param {unknown} ward
	 */
	wardResetSuccess: RequiredParams<'ward'>
	/**
	 * C​O​N​ ​O​m​b​i​ ​l​a​k​o​ ​l​a​ ​k​u​b​a​d​i​l​i​ ​P​I​N​ ​l​i​m​e​f​a​n​i​k​i​w​a​.​
​0​.​ ​R​u​d​i​
​9​.​ ​T​o​k​a
	 */
	pinChangeSuccess: string
	/**
	 * E​N​D​ ​K​u​l​i​k​u​w​a​ ​n​a​ ​t​a​t​i​z​o​ ​l​a​ ​k​u​b​a​d​i​l​i​ ​P​I​N​ ​y​a​k​o​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	pinChangeError: string
}

export type NamespaceProfileTranslation = {
	/**
	 * C​O​N​ ​W​a​s​i​f​u​ ​w​a​n​g​u​
​1​.​ ​W​e​k​a​ ​j​i​n​a​
​2​.​ ​W​e​k​a​ ​j​i​n​s​i​a​
​3​.​ ​W​e​k​a​ ​m​w​a​k​a​ ​w​a​ ​k​u​z​a​l​i​w​a​
​4​.​ ​W​e​k​a​ ​e​n​e​o​
​5​.​ ​A​n​g​a​l​i​a​ ​W​a​s​i​f​u​
​0​.​ ​R​u​d​i
	 */
	profileMenu: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​m​a​j​i​n​a​ ​y​a​k​o​ ​y​a​ ​k​w​a​n​z​a​:​
​0​.​ ​R​u​d​i
	 */
	enteringGivenNames: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​j​i​n​a​ ​l​a​k​o​ ​l​a​ ​f​a​m​i​l​i​a​:​
​0​.​ ​R​u​d​i
	 */
	enteringFamilyName: string
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​j​i​n​s​i​a​:​
​1​.​ ​M​w​a​n​a​u​m​e​
​2​.​ ​M​w​a​n​a​m​k​e​
​3​.​ ​N​y​i​n​g​i​n​e​
​0​.​ ​R​u​d​i
	 */
	selectingGender: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​m​w​a​k​a​ ​w​a​k​o​ ​w​a​ ​k​u​z​a​l​i​w​a​:​
​0​.​ ​R​u​d​i
	 */
	enteringYOB: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​e​n​e​o​ ​l​a​k​o​:​
​0​.​ ​R​u​d​i
	 */
	enteringLocation: string
	/**
	 * C​O​N​ ​T​a​f​a​d​h​a​l​i​ ​w​e​k​a​ ​P​I​N​ ​y​a​k​o​:​
​0​.​ ​R​u​d​i
	 */
	enteringProfileChangePin: string
	/**
	 * C​O​N​ ​T​a​f​a​d​h​a​l​i​ ​w​e​k​a​ ​P​I​N​ ​y​a​k​o​:​
​0​.​ ​R​u​d​i
	 */
	authorizingProfileView: string
	/**
	 * C​O​N​ ​O​m​b​i​ ​l​a​k​o​ ​l​a​ ​k​u​w​e​k​a​ ​w​a​s​i​f​u​ ​l​i​m​e​f​a​n​i​k​i​w​a​.​
​0​.​ ​R​u​d​i​
​9​.​ ​O​n​d​o​k​a
	 */
	profileChangeSuccess: string
	/**
	 * E​N​D​ ​T​a​t​i​z​o​ ​l​i​m​e​t​o​k​e​a​ ​w​a​k​a​t​i​ ​w​a​ ​k​u​w​e​k​a​ ​w​a​s​i​f​u​ ​w​a​k​o​,​ ​t​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	changeError: string
	/**
	 * C​O​N​ ​T​a​f​a​d​h​a​l​i​ ​w​e​k​a​ ​P​I​N​ ​y​a​k​o​:​
​0​.​ ​R​u​d​i
	 */
	enteringProfileViewPin: string
	/**
	 * C​O​N​ ​W​a​s​i​f​u​:​
​{​n​a​m​e​|​p​r​o​f​i​l​e​V​a​l​u​e​}​
​{​g​e​n​d​e​r​|​p​r​o​f​i​l​e​V​a​l​u​e​}​
​{​a​g​e​|​p​r​o​f​i​l​e​V​a​l​u​e​}​
​{​l​o​c​a​t​i​o​n​|​p​r​o​f​i​l​e​V​a​l​u​e​}​
​0​.​ ​R​u​d​i
	 * @param {unknown} age
	 * @param {unknown} gender
	 * @param {unknown} location
	 * @param {unknown} name
	 */
	displayingProfile: RequiredParams<'age|profileValue' | 'gender|profileValue' | 'location|profileValue' | 'name|profileValue'>
}

export type NamespaceRegistrationTranslation = {
	/**
	 * C​O​N​ ​K​a​r​i​b​u​ ​S​a​r​a​f​u​ ​N​e​t​w​o​r​k​!​
​{​l​a​n​g​u​a​g​e​s​}​
​
​0​0​.​O​n​d​o​k​a​
​1​1​.​ ​M​b​e​l​e
	 * @param {unknown} languages
	 */
	welcome: RequiredParams<'languages'>
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​l​u​g​h​a​:​
​{​l​a​n​g​u​a​g​e​s​}​
​
​1​1​.​ ​M​b​e​l​e​
​2​2​.​ ​R​u​d​i​
​0​0​.​O​n​d​o​k​a
	 * @param {unknown} languages
	 */
	secondLanguageSet: RequiredParams<'languages'>
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​l​u​g​h​a​:​
​{​l​a​n​g​u​a​g​e​s​}​
​
​2​2​.​ ​R​u​d​i​
​0​0​.​O​n​d​o​k​a
	 * @param {unknown} languages
	 */
	thirdLanguageSet: RequiredParams<'languages'>
	/**
	 * E​N​D​ ​A​k​a​u​n​t​i​ ​y​a​k​o​ ​y​a​ ​S​a​r​a​f​u​ ​i​n​a​t​a​y​a​r​i​s​h​w​a​.​ ​U​t​a​p​o​k​e​a​ ​u​j​u​m​b​e​ ​w​a​ ​S​M​S​ ​a​k​a​u​n​t​i​ ​y​a​k​o​ ​i​k​i​w​a​ ​t​a​y​a​r​i​.
	 */
	accountCreated: string
	/**
	 * E​N​D​ ​S​a​r​a​f​u​ ​i​n​a​ ​h​i​t​i​l​a​f​u​ ​z​a​ ​k​i​m​i​t​a​m​b​o​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	accountCreationFailed: string
	/**
	 * E​N​D​ ​A​s​a​n​t​e​ ​k​w​a​ ​k​u​t​u​m​i​a​ ​h​u​d​u​m​a​ ​y​a​ ​S​a​r​a​f​u​.
	 */
	exit: string
}

export type NamespaceSettingsTranslation = {
	/**
	 * C​O​N​ ​A​k​a​u​n​t​i​ ​y​a​n​g​u​
​1​.​ ​W​a​s​i​f​u​ ​w​a​n​g​u​
​2​.​ ​B​a​d​i​l​i​ ​l​u​g​h​a​
​3​.​ ​A​n​g​a​l​i​a​ ​s​a​l​i​o​
​4​.​ ​T​a​a​r​i​f​a​ ​y​a​ ​m​a​t​u​m​i​z​i​
​5​.​ ​M​i​p​a​n​g​i​l​i​o​ ​y​a​ ​P​I​N​
​
​0​.​ ​R​u​d​i
	 */
	settingsMenu: string
	/**
	 * C​O​N​ ​S​a​l​i​o​:​ ​{​b​a​l​a​n​c​e​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​
​1​.​ ​T​u​m​a​
​2​.​ ​S​a​r​a​f​u​ ​y​a​n​g​u​
​3​.​ ​A​k​a​u​n​t​i​ ​y​a​n​g​u​
​4​.​ ​U​s​a​i​d​i​z​i
	 * @param {unknown} balance
	 * @param {unknown} symbol
	 */
	mainMenu: RequiredParams<'balance|currency' | 'symbol'>
}

export type NamespaceSocialRecoveryTranslation = {
	/**
	 * E​N​D​ ​P​I​N​ ​y​a​k​o​ ​i​m​e​f​u​n​g​w​a​.​ ​T​a​f​a​d​h​a​l​i​ ​p​i​g​a​ ​n​a​m​b​a​:​ ​{​s​u​p​p​o​r​t​P​h​o​n​e​}​.
	 * @param {unknown} supportPhone
	 */
	accountBlocked: RequiredParams<'supportPhone'>
	/**
	 * C​O​N​ ​W​e​k​a​ ​n​a​m​b​a​ ​y​a​ ​s​i​m​u​ ​y​a​ ​m​l​i​n​z​i​ ​u​n​a​y​e​t​a​k​a​ ​k​u​o​n​d​o​a​:​
​0​.​ ​R​u​d​i
	 */
	enteringGuardianToRemove: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​n​a​m​b​a​ ​y​a​ ​s​i​m​u​ ​y​a​ ​m​l​i​n​z​i​ ​u​n​a​y​e​t​a​k​a​ ​k​u​o​n​g​e​z​a​:​
​0​.​ ​R​u​d​i
	 */
	enteringNewGuardian: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​P​I​N​ ​y​a​k​o​ ​i​l​i​ ​k​u​o​n​g​e​z​a​ ​m​l​i​n​z​i​:​
​0​.​ ​R​u​d​i
	 */
	enteringPinAG: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​P​I​N​ ​y​a​k​o​ ​i​l​i​ ​k​u​o​n​d​o​a​ ​m​l​i​n​z​i​:​
​0​.​ ​R​u​d​i
	 */
	enteringPinRG: string
	/**
	 * C​O​N​ ​W​e​k​a​ ​P​I​N​ ​y​a​k​o​ ​i​l​i​ ​k​u​o​n​a​ ​w​a​l​i​n​z​i​ ​w​a​k​o​:​
​0​.​ ​R​u​d​i
	 */
	enteringPinVG: string
	/**
	 * E​N​D​ ​A​s​a​n​t​e​ ​k​w​a​ ​k​u​t​u​m​i​a​ ​S​a​r​a​f​u​.​ ​K​w​a​h​e​r​i​.
	 */
	exit: string
	/**
	 * E​N​D​ ​K​u​l​i​k​u​w​a​ ​n​a​ ​t​a​t​i​z​o​ ​k​a​t​i​k​a​ ​k​u​o​n​g​e​z​a​ ​{​g​u​a​r​d​i​a​n​}​ ​k​u​w​a​ ​m​l​i​n​z​i​ ​w​a​k​o​.
	 * @param {unknown} guardian
	 */
	guardianAdditionError: RequiredParams<'guardian'>
	/**
	 * C​O​N​ ​{​g​u​a​r​d​i​a​n​}​ ​a​m​e​o​n​g​e​z​w​a​ ​k​u​w​a​ ​m​l​i​n​z​i​ ​w​a​k​o​.​
​0​.​ ​R​u​d​i​
​9​.​ ​O​n​d​o​k​a
	 * @param {unknown} guardian
	 */
	guardianAdditionSuccess: RequiredParams<'guardian'>
	/**
	 * E​N​D​ ​K​u​l​i​k​u​w​a​ ​n​a​ ​t​a​t​i​z​o​ ​k​a​t​i​k​a​ ​k​u​o​n​d​o​a​ ​{​g​u​a​r​d​i​a​n​}​ ​k​u​w​a​ ​m​l​i​n​z​i​ ​w​a​k​o​.
	 * @param {unknown} guardian
	 */
	guardianRemovalError: RequiredParams<'guardian'>
	/**
	 * C​O​N​ ​{​g​u​a​r​d​i​a​n​}​ ​a​m​e​o​n​d​o​l​e​w​a​ ​k​u​w​a​ ​m​l​i​n​z​i​ ​w​a​k​o​.​
​0​.​ ​R​u​d​i​
​9​.​ ​O​n​d​o​k​a
	 * @param {unknown} guardian
	 */
	guardianRemovalSuccess: RequiredParams<'guardian'>
	/**
	 * E​N​D​ ​K​u​l​i​k​u​w​a​ ​n​a​ ​t​a​t​i​z​o​ ​k​a​t​i​k​a​ ​k​u​a​n​g​a​l​i​a​ ​w​a​l​i​n​z​i​ ​w​a​k​o​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	loadError: string
	/**
	 * C​O​N​ ​W​a​l​i​n​z​i​ ​w​a​k​o​ ​n​i​:​
​{​g​u​a​r​d​i​a​n​s​}​
​0​.​ ​R​u​d​i​
​9​.​ ​O​n​d​o​k​a
	 * @param {unknown} guardians
	 */
	pinGuardiansLoaded: RequiredParams<'guardians'>
	/**
	 * C​O​N​ ​U​l​i​n​z​i​ ​w​a​ ​P​I​N​:​
​1​.​ ​O​n​g​e​z​a​ ​m​l​i​n​z​i​
​2​.​ ​O​n​d​o​a​ ​m​l​i​n​z​i​
​3​.​ ​A​n​g​a​l​i​a​ ​w​a​l​i​n​z​i​
​0​.​ ​R​u​d​i
	 */
	socialRecoveryMenu: string
}

export type NamespaceStatementTranslation = {
	/**
	 * E​N​D​ ​A​k​a​u​n​t​i​ ​y​a​k​o​ ​i​m​e​f​u​n​g​w​a​.​ ​K​w​a​ ​u​s​a​i​d​i​z​i​,​ ​t​a​f​a​d​h​a​l​i​ ​p​i​g​a​ ​s​i​m​u​ ​k​w​a​:​ ​{​s​u​p​p​o​r​t​P​h​o​n​e​}​.
	 * @param {unknown} supportPhone
	 */
	accountBlocked: RequiredParams<'supportPhone'>
	/**
	 * C​O​N​ ​W​e​k​a​ ​P​I​N​ ​k​u​o​n​a​ ​t​a​a​r​i​f​a​ ​y​a​ ​a​k​a​u​n​t​i​ ​y​a​k​o​:​
​0​.​ ​R​u​d​i
	 */
	enteringPin: string
	/**
	 * E​N​D​ ​A​s​a​n​t​e​ ​k​w​a​ ​k​u​t​u​m​i​a​ ​h​u​d​u​m​a​ ​y​a​ ​S​a​r​a​f​u​.
	 */
	exit: string
	/**
	 * C​O​N​ ​{​t​r​a​n​s​a​c​t​i​o​n​s​}​
​
​1​1​.​M​b​e​l​e​
​0​0​.​ ​O​n​d​o​k​a
	 * @param {unknown} transactions
	 */
	firstTransactionSet: RequiredParams<'transactions'>
	/**
	 * E​N​D​ ​K​o​s​a​ ​l​i​m​e​t​o​k​e​a​ ​w​a​k​a​t​i​ ​w​a​ ​k​u​a​n​g​a​l​i​a​ ​t​a​a​r​i​f​a​ ​y​a​ ​a​k​a​u​n​t​i​ ​y​a​k​o​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	loadError: string
	/**
	 * C​O​N​ ​S​a​l​i​o​:​ ​{​b​a​l​a​n​c​e​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​
​1​.​ ​T​u​m​a​
​2​.​ ​S​a​r​a​f​u​ ​y​a​n​g​u​
​3​.​ ​A​k​a​u​n​t​i​ ​y​a​n​g​u​
​4​.​ ​U​s​a​i​d​i​z​i
	 * @param {unknown} balance
	 * @param {unknown} symbol
	 */
	mainMenu: RequiredParams<'balance|currency' | 'symbol'>
	/**
	 * C​O​N​ ​{​t​r​a​n​s​a​c​t​i​o​n​s​}​
​
​1​1​.​ ​M​b​e​l​e​
​2​2​.​ ​N​y​u​m​a​
​0​0​.​ ​O​n​d​o​k​a
	 * @param {unknown} transactions
	 */
	secondTransactionSet: RequiredParams<'transactions'>
	/**
	 * C​O​N​ ​{​t​r​a​n​s​a​c​t​i​o​n​s​}​
​
​2​2​.​ ​N​y​u​m​a​
​0​0​.​ ​O​n​d​o​k​a
	 * @param {unknown} transactions
	 */
	thirdTransactionSet: RequiredParams<'transactions'>
}

export type NamespaceTransferTranslation = {
	/**
	 * E​N​D​ ​P​I​N​ ​y​a​k​o​ ​i​m​e​f​u​n​g​w​a​.​ ​K​w​a​ ​u​s​a​i​d​i​z​i​ ​t​a​f​a​d​h​a​l​i​ ​p​i​g​a​ ​s​i​m​u​ ​k​w​a​:​ ​{​s​u​p​p​o​r​t​P​h​o​n​e​}​.
	 * @param {unknown} supportPhone
	 */
	accountBlocked: RequiredParams<'supportPhone'>
	/**
	 * C​O​N​ ​{​r​e​c​i​p​i​e​n​t​}​ ​a​t​a​p​o​k​e​a​ ​{​a​m​o​u​n​t​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​ ​k​u​t​o​k​a​ ​k​w​a​ ​{​s​e​n​d​e​r​}​
​T​a​f​a​d​h​a​l​i​ ​w​e​k​a​ ​P​I​N​ ​y​a​k​o​ ​k​u​d​h​i​b​i​t​i​s​h​a​:
	 * @param {unknown} amount
	 * @param {unknown} recipient
	 * @param {unknown} sender
	 * @param {unknown} symbol
	 */
	enteringPin: RequiredParams<'amount|currency' | 'recipient' | 'sender' | 'symbol'>
	/**
	 * C​O​N​ ​K​i​w​a​n​g​o​ ​c​h​a​ ​j​u​u​:​ ​{​s​p​e​n​d​a​b​l​e​|​c​u​r​r​e​n​c​y​}​
​W​e​k​a​ ​k​i​w​a​n​g​o​:​
​0​.​ ​R​u​d​i
	 * @param {unknown} spendable
	 */
	enteringAmount: RequiredParams<'spendable|currency'>
	/**
	 * C​O​N​ ​W​e​k​a​ ​n​a​m​b​a​r​i​ ​y​a​ ​s​i​m​u​:​
​0​.​ ​R​u​d​i
	 */
	enteringRecipient: string
	/**
	 * C​O​N​ ​{​r​e​c​i​p​i​e​n​t​}​ ​h​a​i​j​a​s​a​j​i​l​i​w​a​ ​a​u​ ​s​i​o​ ​s​a​h​i​h​i​,​ ​t​a​f​a​d​h​a​l​i​ ​w​e​k​a​ ​t​e​n​a​:​
​1​.​K​a​r​i​b​i​s​h​a​ ​k​w​a​ ​m​a​t​a​n​d​a​o​ ​w​a​ ​S​a​r​a​f​u​.​
​9​.​ ​O​n​d​o​k​a
	 * @param {unknown} recipient
	 */
	invalidRecipient: RequiredParams<'recipient'>
	/**
	 * E​N​D​ ​O​m​b​i​ ​l​a​k​o​ ​l​a​ ​k​u​m​w​a​l​i​k​a​ ​{​i​n​v​i​t​e​e​}​ ​k​w​a​ ​m​a​t​a​n​d​a​o​ ​w​a​ ​S​a​r​a​f​u​ ​h​a​l​i​k​u​f​a​u​l​u​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 * @param {unknown} invitee
	 */
	inviteError: RequiredParams<'invitee'>
	/**
	 * E​N​D​ ​O​m​b​i​ ​l​a​k​o​ ​l​a​ ​k​u​m​w​a​l​i​k​a​ ​{​i​n​v​i​t​e​e​}​ ​k​w​a​ ​m​a​t​a​n​d​a​o​ ​w​a​ ​S​a​r​a​f​u​ ​l​i​m​e​t​u​m​w​a​.
	 * @param {unknown} invitee
	 */
	inviteSuccess: RequiredParams<'invitee'>
	/**
	 * C​O​N​ ​S​a​l​i​o​:​ ​{​b​a​l​a​n​c​e​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​
​1​.​ ​T​u​m​a​
​2​.​ ​S​a​r​a​f​u​ ​y​a​n​g​u​
​3​.​ ​A​k​a​u​n​t​i​ ​y​a​n​g​u​
​4​.​ ​U​s​a​i​d​i​z​i
	 * @param {unknown} balance
	 * @param {unknown} symbol
	 */
	mainMenu: RequiredParams<'balance|currency' | 'symbol'>
	/**
	 * E​N​D​ ​O​m​b​i​ ​l​a​k​o​ ​h​a​l​i​k​u​f​a​u​l​u​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	transferError: string
	/**
	 * E​N​D​ ​O​m​b​i​ ​l​a​k​o​ ​l​i​m​e​t​u​m​w​a​.​ ​{​r​e​c​i​p​i​e​n​t​}​ ​a​t​a​p​o​k​e​a​ ​{​a​m​o​u​n​t​|​c​u​r​r​e​n​c​y​}​ ​{​s​y​m​b​o​l​}​ ​k​u​t​o​k​a​ ​k​w​a​ ​{​s​e​n​d​e​r​}​.
	 * @param {unknown} amount
	 * @param {unknown} recipient
	 * @param {unknown} sender
	 * @param {unknown} symbol
	 */
	transferInitiated: RequiredParams<'amount|currency' | 'recipient' | 'sender' | 'symbol'>
}

export type NamespaceVoucherTranslation = {
	/**
	 * C​O​N​ ​S​a​r​a​f​u​ ​y​a​n​g​u​
​1​.​ ​C​h​a​g​u​a​ ​S​a​r​a​f​u​
​2​.​ ​M​a​e​l​e​z​o​ ​y​a​ ​S​a​r​a​f​u​
​0​.​ ​R​u​d​i
	 */
	voucherMenu: string
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​n​a​m​b​a​r​i​ ​a​u​ ​i​s​h​a​r​a​ ​k​u​t​o​k​a​ ​k​w​a​ ​s​a​l​i​o​ ​z​a​k​o​:​
​{​v​o​u​c​h​e​r​s​}​
​
​0​.​ ​R​u​d​i​
​1​1​.​ ​M​b​e​l​e​
​0​0​.​ ​O​n​d​o​k​a
	 * @param {unknown} vouchers
	 */
	selectingVoucher: RequiredParams<'vouchers'>
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​n​a​m​b​a​r​i​ ​a​u​ ​i​s​h​a​r​a​ ​k​u​t​o​k​a​ ​k​w​a​ ​s​a​l​i​o​ ​z​a​k​o​:​
​{​v​o​u​c​h​e​r​s​}​
​
​1​1​.​ ​M​b​e​l​e​
​2​2​.​ ​R​u​d​i​
​0​0​.​ ​O​n​d​o​k​a
	 * @param {unknown} vouchers
	 */
	secondSet: RequiredParams<'vouchers'>
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​n​a​m​b​a​r​i​ ​a​u​ ​i​s​h​a​r​a​ ​k​u​t​o​k​a​ ​k​w​a​ ​s​a​l​i​o​ ​z​a​k​o​:​
​{​v​o​u​c​h​e​r​s​}​
​
​2​2​.​ ​R​u​d​i​
​0​0​.​ ​O​n​d​o​k​a
	 * @param {unknown} vouchers
	 */
	thirdSet: RequiredParams<'vouchers'>
	/**
	 * C​O​N​ ​W​e​k​a​ ​P​I​N​ ​i​l​i​ ​k​u​t​h​i​b​i​t​i​s​h​a​ ​c​h​a​g​u​o​:​
​{​s​y​m​b​o​l​}​ ​{​n​a​m​e​}​
​{​c​o​n​t​a​c​t​}​ ​{​l​o​c​a​t​i​o​n​}​
​{​d​e​s​c​r​i​p​t​i​o​n​}​
​
​0​.​ ​R​u​d​i​
​0​0​.​ ​O​n​d​o​k​a
	 * @param {unknown} contact
	 * @param {unknown} description
	 * @param {unknown} location
	 * @param {unknown} name
	 * @param {unknown} symbol
	 */
	enteringPin: RequiredParams<'contact' | 'description' | 'location' | 'name' | 'symbol'>
	/**
	 * C​O​N​ ​H​o​n​g​e​r​a​!​ ​{​s​y​m​b​o​l​}​ ​n​i​ ​S​a​r​a​f​u​ ​i​n​a​y​o​t​u​m​i​k​a​ ​s​a​s​a​.​
​0​.​ ​R​u​d​i​ ​
​9​.​ ​O​n​d​o​k​a
	 * @param {unknown} symbol
	 */
	setSuccess: RequiredParams<'symbol'>
	/**
	 * E​N​D​ ​K​u​l​i​k​u​w​a​ ​n​a​ ​t​a​t​i​z​o​ ​k​w​a​ ​k​u​c​h​a​g​u​a​ ​S​a​r​a​f​u​.​ ​J​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	setError: string
	/**
	 * C​O​N​ ​{​s​y​m​b​o​l​}​ ​{​n​a​m​e​}​
​{​c​o​n​t​a​c​t​}​ ​{​l​o​c​a​t​i​o​n​}​
​{​d​e​s​c​r​i​p​t​i​o​n​}​
​
​0​.​ ​R​u​d​i
	 * @param {unknown} contact
	 * @param {unknown} description
	 * @param {unknown} location
	 * @param {unknown} name
	 * @param {unknown} symbol
	 */
	voucherDetails: RequiredParams<'contact' | 'description' | 'location' | 'name' | 'symbol'>
	/**
	 * E​N​D​ ​P​I​N​ ​y​a​k​o​ ​i​m​e​f​u​n​g​w​a​.​ ​K​w​a​ ​u​s​a​i​d​i​z​i​ ​t​a​f​a​d​h​a​l​i​ ​p​i​g​a​ ​s​i​m​u​ ​k​w​a​:​ ​{​s​u​p​p​o​r​t​P​h​o​n​e​}​.
	 * @param {unknown} supportPhone
	 */
	accountBlocked: RequiredParams<'supportPhone'>
	/**
	 * E​N​D​ ​A​s​a​n​t​e​ ​k​w​a​ ​k​u​t​u​m​i​a​ ​h​u​d​u​m​a​ ​y​a​ ​S​a​r​a​f​u​.​ ​K​w​a​h​e​r​i​.
	 */
	exit: string
}

export type Namespaces =
	| 'auth'
	| 'balances'
	| 'feedback'
	| 'helpers'
	| 'language'
	| 'main'
	| 'pin'
	| 'profile'
	| 'registration'
	| 'settings'
	| 'socialRecovery'
	| 'statement'
	| 'transfer'
	| 'voucher'

type DisallowNamespaces = {
	/**
	 * reserved for 'auth'-namespace\
	 * you need to use the `./auth/index.ts` file instead
	 */
	auth?: "[typesafe-i18n] reserved for 'auth'-namespace. You need to use the `./auth/index.ts` file instead."

	/**
	 * reserved for 'balances'-namespace\
	 * you need to use the `./balances/index.ts` file instead
	 */
	balances?: "[typesafe-i18n] reserved for 'balances'-namespace. You need to use the `./balances/index.ts` file instead."

	/**
	 * reserved for 'feedback'-namespace\
	 * you need to use the `./feedback/index.ts` file instead
	 */
	feedback?: "[typesafe-i18n] reserved for 'feedback'-namespace. You need to use the `./feedback/index.ts` file instead."

	/**
	 * reserved for 'helpers'-namespace\
	 * you need to use the `./helpers/index.ts` file instead
	 */
	helpers?: "[typesafe-i18n] reserved for 'helpers'-namespace. You need to use the `./helpers/index.ts` file instead."

	/**
	 * reserved for 'language'-namespace\
	 * you need to use the `./language/index.ts` file instead
	 */
	language?: "[typesafe-i18n] reserved for 'language'-namespace. You need to use the `./language/index.ts` file instead."

	/**
	 * reserved for 'main'-namespace\
	 * you need to use the `./main/index.ts` file instead
	 */
	main?: "[typesafe-i18n] reserved for 'main'-namespace. You need to use the `./main/index.ts` file instead."

	/**
	 * reserved for 'pin'-namespace\
	 * you need to use the `./pin/index.ts` file instead
	 */
	pin?: "[typesafe-i18n] reserved for 'pin'-namespace. You need to use the `./pin/index.ts` file instead."

	/**
	 * reserved for 'profile'-namespace\
	 * you need to use the `./profile/index.ts` file instead
	 */
	profile?: "[typesafe-i18n] reserved for 'profile'-namespace. You need to use the `./profile/index.ts` file instead."

	/**
	 * reserved for 'registration'-namespace\
	 * you need to use the `./registration/index.ts` file instead
	 */
	registration?: "[typesafe-i18n] reserved for 'registration'-namespace. You need to use the `./registration/index.ts` file instead."

	/**
	 * reserved for 'settings'-namespace\
	 * you need to use the `./settings/index.ts` file instead
	 */
	settings?: "[typesafe-i18n] reserved for 'settings'-namespace. You need to use the `./settings/index.ts` file instead."

	/**
	 * reserved for 'socialRecovery'-namespace\
	 * you need to use the `./socialRecovery/index.ts` file instead
	 */
	socialRecovery?: "[typesafe-i18n] reserved for 'socialRecovery'-namespace. You need to use the `./socialRecovery/index.ts` file instead."

	/**
	 * reserved for 'statement'-namespace\
	 * you need to use the `./statement/index.ts` file instead
	 */
	statement?: "[typesafe-i18n] reserved for 'statement'-namespace. You need to use the `./statement/index.ts` file instead."

	/**
	 * reserved for 'transfer'-namespace\
	 * you need to use the `./transfer/index.ts` file instead
	 */
	transfer?: "[typesafe-i18n] reserved for 'transfer'-namespace. You need to use the `./transfer/index.ts` file instead."

	/**
	 * reserved for 'voucher'-namespace\
	 * you need to use the `./voucher/index.ts` file instead
	 */
	voucher?: "[typesafe-i18n] reserved for 'voucher'-namespace. You need to use the `./voucher/index.ts` file instead."
}

export type TranslationFunctions = {
	auth: {
		/**
		 * END PIN yako imefungwa. Kwa usaidizi tafadhali piga simu kwa: {supportPhone}.
		 */
		accountBlocked: (arg: { supportPhone: unknown }) => LocalizedString
		/**
		 * END Akaunti yako ya Sarafu bado inatayarishwa. Utapokea ujumbe wa SMS akaunti yako ikiwa tayari.
		 */
		processingAccount: () => LocalizedString
		/**
		 * CON Tafadhali weka PIN yenye nambari nne:
	00. Ondoka
		 */
		enteringPin: () => LocalizedString
		/**
		 * CON Weka PIN yako tena:
	00. Ondoka
		 */
		confirmingPin: () => LocalizedString
		/**
		 * CON Salio: {balance|currency} {symbol}
	1. Tuma
	2. Sarafu yangu
	3. Akaunti yangu
	4. Usaidizi
		 */
		mainMenu: (arg: { balance: unknown, symbol: unknown }) => LocalizedString
		/**
		 * END Tafadhali jaribu tena baada ya dakika chache. Kama tatizo linaendelea, tafadhali wasiliana na {supportNumber|phone}.
		 */
		activationError: (arg: { supportNumber: unknown }) => LocalizedString
		/**
		 * END Asante kwa kutumia Sarafu. Kwaheri.
		 */
		exit: () => LocalizedString
	}
	balances: {
		/**
		 * END PIN yako imefungwa. Kwa msaada tafadhali piga: {supportPhone}.
		 */
		accountBlocked: (arg: { supportPhone: unknown }) => LocalizedString
		/**
		 * CON Salio langu
	1. Salio langu
	2. Salio la kikundi
	0. Rudi
		 */
		balancesMenu: () => LocalizedString
		/**
		 * CON Tafadhali weka PIN yako:
	0. Rudi
		 */
		enteringPinA: () => LocalizedString
		/**
		 * CON Tafadhali weka PIN yako:
	0. Rudi
		 */
		enteringPinC: () => LocalizedString
		/**
		 * END Asante kwa kutumia Sarafu. Kwaheri.
		 */
		exit: () => LocalizedString
		/**
		 * END Tatizo limetokea wakati wa kuangali salio lako. Tafadhali jaribu tena baadaye.
		 */
		loadAError: () => LocalizedString
		/**
		 * END Tatizo limetokea wakati wa kuangalia salio la kikundi. Tafadhali jaribu tena baadaye.
		 */
		loadCError: () => LocalizedString
		/**
		 * CON Salio lako ni {balance|currency} {symbol}.
	0. Rudi
	9. Ondoka
		 */
		loadedASuccess: (arg: { balance: unknown, symbol: unknown }) => LocalizedString
		/**
		 * CON Salio la kikundi ni {balance|currency} {symbol}.
	0. Rudi
	9. Ondoka
		 */
		loadedCSuccess: (arg: { balance: unknown, symbol: unknown }) => LocalizedString
	}
	feedback: {
		/**
		 * CON lugha '{feedback}' sio sahihi.
	Chagua lugha:
	{languages}

	11. Mbele
	22. Rudi
	00.Ondoka
		 */
		invalidLanguageOption: (arg: { feedback: unknown, languages: unknown }) => LocalizedString
	}
	helpers: {
		/**
		 * Hamna Sarafu nyengine zilizopo.
	22. Rudi
	00. Ondoka
		 */
		noMoreVouchers: () => LocalizedString
		gender: {
			/**
			 * Jinsia: Mwanaume
			 */
			MALE: () => LocalizedString
			/**
			 * Jinsia: Mwanamke
			 */
			FEMALE: () => LocalizedString
		}
		/**
		 * Umri:
		 */
		age: () => LocalizedString
		/**
		 * Jina:
		 */
		name: () => LocalizedString
		/**
		 * Eneo:
		 */
		location: () => LocalizedString
		/**
		 * Haipo
		 */
		notProvided: () => LocalizedString
		/**
		 * Ulituma {value|currency} {symbol} kwa {recipient} {time},  aliyepokea: {sender}.
		 */
		debit: (arg: { recipient: unknown, sender: unknown, symbol: unknown, time: unknown, value: unknown }) => LocalizedString
		/**
		 * Ulipokea {value|currency} {symbol} kutoka kwa {sender} {time}, aliyetuma: {recipient}.
		 */
		credit: (arg: { recipient: unknown, sender: unknown, symbol: unknown, time: unknown, value: unknown }) => LocalizedString
		/**
		 * Hamna taarifa zaidi ya malipo.
		 */
		noMoreTransactions: () => LocalizedString
		/**
		 * Hamna lugha zaidi zilizopo.
		 */
		noMoreLanguageOptions: () => LocalizedString
		/**
		 * Hamna walinzi zaidi.
		 */
		noMoreGuardians: () => LocalizedString
	}
	language: {
		/**
		 * END PIN yako imefungwa. Kwa usaidizi tafadhali piga simu kwa: {supportPhone}.
		 */
		accountBlocked: (arg: { supportPhone: unknown }) => LocalizedString
		/**
		 * END Tatizo limetokea wakati wa kubadilisha lugha, tafadhali jaribu tena baadaye.
		 */
		changeError: () => LocalizedString
		/**
		 * CON Ombi lako la kubadilisha lugha limefanikiwa.
	0. Rudi
	9. Ondoka
		 */
		changeSuccess: () => LocalizedString
		/**
		 * CON Tafadhali weka PIN yenye nambari nne:
	0. Rudi
		 */
		enteringPin: () => LocalizedString
		/**
		 * END Asante kwa kutumia Sarafu. Kwaheri.
		 */
		exit: () => LocalizedString
		/**
		 * CON Chagua lugha:
	{languages}

	11. Mbele
	22. Rudi
	00.Ondoka
		 */
		secondLanguageSet: (arg: { languages: unknown }) => LocalizedString
		/**
		 * CON Chagua lugha:
	{languages}

	00.Ondoka
	11. Mbele
		 */
		selectingLanguage: (arg: { languages: unknown }) => LocalizedString
		/**
		 * CON Chagua lugha:
	{languages}

	22. Rudi
	00.Ondoka
		 */
		thirdLanguageSet: (arg: { languages: unknown }) => LocalizedString
	}
	main: {
		/**
		 * CON Salio: {balance|currency} {symbol}
	1. Tuma
	2. Sarafu yangu
	3. Akaunti yangu
	4. Usaidizi
		 */
		mainMenu: (arg: { balance: unknown, symbol: unknown }) => LocalizedString
	}
	pin: {
		/**
		 * END PIN yako imefungwa. Kwa usaidizi tafadhali piga: {supportPhone}.
		 */
		accountBlocked: (arg: { supportPhone: unknown }) => LocalizedString
		/**
		 * END Kulikuwa na tatizo la kubadili PIN yako. Tafadhali jaribu tena baadaye.
		 */
		changeError: () => LocalizedString
		/**
		 * CON Thibitisha PIN yako mpya:
	0. Rudi
		 */
		confirmNewPin: () => LocalizedString
		/**
		 * CON Weka PIN mpya ya nne nambari:
	0. Rudi
		 */
		enteringNewPin: () => LocalizedString
		/**
		 * CON Weka PIN yako ya zamani:
	0. Rudi
		 */
		enteringOldPin: () => LocalizedString
		/**
		 * CON Weka PIN yako ili uanze kubadili:
	0. Rudi
		 */
		enteringPinR: () => LocalizedString
		/**
		 * CON Weka nambari ya simu ya mwenzio:
	0. Rudi
		 */
		enteringWard: () => LocalizedString
		/**
		 * CON Mipangilio ya PIN:
	1. Badili PIN
	2. Badili PIN ya mwenzio
	3. Linda PIN yangu
	0. Rudi
		 */
		pinManagementMenu: () => LocalizedString
		/**
		 * CON Ulinzi wa PIN:
	1. Ongeza mlinzi
	2. Ondoa mlinzi
	3. Angalia walinzi
	0. Rudi
		 */
		socialRecoveryMenu: () => LocalizedString
		/**
		 * END Kulikuwa na tatizo la kubadili PIN ya {ward}.
		 */
		wardResetError: (arg: { ward: unknown }) => LocalizedString
		/**
		 * CON Ombi lako la kubadili PIN ya {ward} limepelekwa.
	0. Rudi
	9. Toka
		 */
		wardResetSuccess: (arg: { ward: unknown }) => LocalizedString
		/**
		 * CON Ombi lako la kubadili PIN limefanikiwa.
	0. Rudi
	9. Toka
		 */
		pinChangeSuccess: () => LocalizedString
		/**
		 * END Kulikuwa na tatizo la kubadili PIN yako. Tafadhali jaribu tena baadaye.
		 */
		pinChangeError: () => LocalizedString
	}
	profile: {
		/**
		 * CON Wasifu wangu
	1. Weka jina
	2. Weka jinsia
	3. Weka mwaka wa kuzaliwa
	4. Weka eneo
	5. Angalia Wasifu
	0. Rudi
		 */
		profileMenu: () => LocalizedString
		/**
		 * CON Weka majina yako ya kwanza:
	0. Rudi
		 */
		enteringGivenNames: () => LocalizedString
		/**
		 * CON Weka jina lako la familia:
	0. Rudi
		 */
		enteringFamilyName: () => LocalizedString
		/**
		 * CON Chagua jinsia:
	1. Mwanaume
	2. Mwanamke
	3. Nyingine
	0. Rudi
		 */
		selectingGender: () => LocalizedString
		/**
		 * CON Weka mwaka wako wa kuzaliwa:
	0. Rudi
		 */
		enteringYOB: () => LocalizedString
		/**
		 * CON Weka eneo lako:
	0. Rudi
		 */
		enteringLocation: () => LocalizedString
		/**
		 * CON Tafadhali weka PIN yako:
	0. Rudi
		 */
		enteringProfileChangePin: () => LocalizedString
		/**
		 * CON Tafadhali weka PIN yako:
	0. Rudi
		 */
		authorizingProfileView: () => LocalizedString
		/**
		 * CON Ombi lako la kuweka wasifu limefanikiwa.
	0. Rudi
	9. Ondoka
		 */
		profileChangeSuccess: () => LocalizedString
		/**
		 * END Tatizo limetokea wakati wa kuweka wasifu wako, tafadhali jaribu tena baadaye.
		 */
		changeError: () => LocalizedString
		/**
		 * CON Tafadhali weka PIN yako:
	0. Rudi
		 */
		enteringProfileViewPin: () => LocalizedString
		/**
		 * CON Wasifu:
	{name|profileValue}
	{gender|profileValue}
	{age|profileValue}
	{location|profileValue}
	0. Rudi
		 */
		displayingProfile: (arg: { age: unknown, gender: unknown, location: unknown, name: unknown }) => LocalizedString
	}
	registration: {
		/**
		 * CON Karibu Sarafu Network!
	{languages}

	00.Ondoka
	11. Mbele
		 */
		welcome: (arg: { languages: unknown }) => LocalizedString
		/**
		 * CON Chagua lugha:
	{languages}

	11. Mbele
	22. Rudi
	00.Ondoka
		 */
		secondLanguageSet: (arg: { languages: unknown }) => LocalizedString
		/**
		 * CON Chagua lugha:
	{languages}

	22. Rudi
	00.Ondoka
		 */
		thirdLanguageSet: (arg: { languages: unknown }) => LocalizedString
		/**
		 * END Akaunti yako ya Sarafu inatayarishwa. Utapokea ujumbe wa SMS akaunti yako ikiwa tayari.
		 */
		accountCreated: () => LocalizedString
		/**
		 * END Sarafu ina hitilafu za kimitambo. Tafadhali jaribu tena baadaye.
		 */
		accountCreationFailed: () => LocalizedString
		/**
		 * END Asante kwa kutumia huduma ya Sarafu.
		 */
		exit: () => LocalizedString
	}
	settings: {
		/**
		 * CON Akaunti yangu
	1. Wasifu wangu
	2. Badili lugha
	3. Angalia salio
	4. Taarifa ya matumizi
	5. Mipangilio ya PIN

	0. Rudi
		 */
		settingsMenu: () => LocalizedString
		/**
		 * CON Salio: {balance|currency} {symbol}
	1. Tuma
	2. Sarafu yangu
	3. Akaunti yangu
	4. Usaidizi
		 */
		mainMenu: (arg: { balance: unknown, symbol: unknown }) => LocalizedString
	}
	socialRecovery: {
		/**
		 * END PIN yako imefungwa. Tafadhali piga namba: {supportPhone}.
		 */
		accountBlocked: (arg: { supportPhone: unknown }) => LocalizedString
		/**
		 * CON Weka namba ya simu ya mlinzi unayetaka kuondoa:
	0. Rudi
		 */
		enteringGuardianToRemove: () => LocalizedString
		/**
		 * CON Weka namba ya simu ya mlinzi unayetaka kuongeza:
	0. Rudi
		 */
		enteringNewGuardian: () => LocalizedString
		/**
		 * CON Weka PIN yako ili kuongeza mlinzi:
	0. Rudi
		 */
		enteringPinAG: () => LocalizedString
		/**
		 * CON Weka PIN yako ili kuondoa mlinzi:
	0. Rudi
		 */
		enteringPinRG: () => LocalizedString
		/**
		 * CON Weka PIN yako ili kuona walinzi wako:
	0. Rudi
		 */
		enteringPinVG: () => LocalizedString
		/**
		 * END Asante kwa kutumia Sarafu. Kwaheri.
		 */
		exit: () => LocalizedString
		/**
		 * END Kulikuwa na tatizo katika kuongeza {guardian} kuwa mlinzi wako.
		 */
		guardianAdditionError: (arg: { guardian: unknown }) => LocalizedString
		/**
		 * CON {guardian} ameongezwa kuwa mlinzi wako.
	0. Rudi
	9. Ondoka
		 */
		guardianAdditionSuccess: (arg: { guardian: unknown }) => LocalizedString
		/**
		 * END Kulikuwa na tatizo katika kuondoa {guardian} kuwa mlinzi wako.
		 */
		guardianRemovalError: (arg: { guardian: unknown }) => LocalizedString
		/**
		 * CON {guardian} ameondolewa kuwa mlinzi wako.
	0. Rudi
	9. Ondoka
		 */
		guardianRemovalSuccess: (arg: { guardian: unknown }) => LocalizedString
		/**
		 * END Kulikuwa na tatizo katika kuangalia walinzi wako. Tafadhali jaribu tena baadaye.
		 */
		loadError: () => LocalizedString
		/**
		 * CON Walinzi wako ni:
	{guardians}
	0. Rudi
	9. Ondoka
		 */
		pinGuardiansLoaded: (arg: { guardians: unknown }) => LocalizedString
		/**
		 * CON Ulinzi wa PIN:
	1. Ongeza mlinzi
	2. Ondoa mlinzi
	3. Angalia walinzi
	0. Rudi
		 */
		socialRecoveryMenu: () => LocalizedString
	}
	statement: {
		/**
		 * END Akaunti yako imefungwa. Kwa usaidizi, tafadhali piga simu kwa: {supportPhone}.
		 */
		accountBlocked: (arg: { supportPhone: unknown }) => LocalizedString
		/**
		 * CON Weka PIN kuona taarifa ya akaunti yako:
	0. Rudi
		 */
		enteringPin: () => LocalizedString
		/**
		 * END Asante kwa kutumia huduma ya Sarafu.
		 */
		exit: () => LocalizedString
		/**
		 * CON {transactions}

	11.Mbele
	00. Ondoka
		 */
		firstTransactionSet: (arg: { transactions: unknown }) => LocalizedString
		/**
		 * END Kosa limetokea wakati wa kuangalia taarifa ya akaunti yako. Tafadhali jaribu tena baadaye.
		 */
		loadError: () => LocalizedString
		/**
		 * CON Salio: {balance|currency} {symbol}
	1. Tuma
	2. Sarafu yangu
	3. Akaunti yangu
	4. Usaidizi
		 */
		mainMenu: (arg: { balance: unknown, symbol: unknown }) => LocalizedString
		/**
		 * CON {transactions}

	11. Mbele
	22. Nyuma
	00. Ondoka
		 */
		secondTransactionSet: (arg: { transactions: unknown }) => LocalizedString
		/**
		 * CON {transactions}

	22. Nyuma
	00. Ondoka
		 */
		thirdTransactionSet: (arg: { transactions: unknown }) => LocalizedString
	}
	transfer: {
		/**
		 * END PIN yako imefungwa. Kwa usaidizi tafadhali piga simu kwa: {supportPhone}.
		 */
		accountBlocked: (arg: { supportPhone: unknown }) => LocalizedString
		/**
		 * CON {recipient} atapokea {amount|currency} {symbol} kutoka kwa {sender}
	Tafadhali weka PIN yako kudhibitisha:
		 */
		enteringPin: (arg: { amount: unknown, recipient: unknown, sender: unknown, symbol: unknown }) => LocalizedString
		/**
		 * CON Kiwango cha juu: {spendable|currency}
	Weka kiwango:
	0. Rudi
		 */
		enteringAmount: (arg: { spendable: unknown }) => LocalizedString
		/**
		 * CON Weka nambari ya simu:
	0. Rudi
		 */
		enteringRecipient: () => LocalizedString
		/**
		 * CON {recipient} haijasajiliwa au sio sahihi, tafadhali weka tena:
	1.Karibisha kwa matandao wa Sarafu.
	9. Ondoka
		 */
		invalidRecipient: (arg: { recipient: unknown }) => LocalizedString
		/**
		 * END Ombi lako la kumwalika {invitee} kwa matandao wa Sarafu halikufaulu. Tafadhali jaribu tena baadaye.
		 */
		inviteError: (arg: { invitee: unknown }) => LocalizedString
		/**
		 * END Ombi lako la kumwalika {invitee} kwa matandao wa Sarafu limetumwa.
		 */
		inviteSuccess: (arg: { invitee: unknown }) => LocalizedString
		/**
		 * CON Salio: {balance|currency} {symbol}
	1. Tuma
	2. Sarafu yangu
	3. Akaunti yangu
	4. Usaidizi
		 */
		mainMenu: (arg: { balance: unknown, symbol: unknown }) => LocalizedString
		/**
		 * END Ombi lako halikufaulu. Tafadhali jaribu tena baadaye.
		 */
		transferError: () => LocalizedString
		/**
		 * END Ombi lako limetumwa. {recipient} atapokea {amount|currency} {symbol} kutoka kwa {sender}.
		 */
		transferInitiated: (arg: { amount: unknown, recipient: unknown, sender: unknown, symbol: unknown }) => LocalizedString
	}
	voucher: {
		/**
		 * CON Sarafu yangu
	1. Chagua Sarafu
	2. Maelezo ya Sarafu
	0. Rudi
		 */
		voucherMenu: () => LocalizedString
		/**
		 * CON Chagua nambari au ishara kutoka kwa salio zako:
	{vouchers}

	0. Rudi
	11. Mbele
	00. Ondoka
		 */
		selectingVoucher: (arg: { vouchers: unknown }) => LocalizedString
		/**
		 * CON Chagua nambari au ishara kutoka kwa salio zako:
	{vouchers}

	11. Mbele
	22. Rudi
	00. Ondoka
		 */
		secondSet: (arg: { vouchers: unknown }) => LocalizedString
		/**
		 * CON Chagua nambari au ishara kutoka kwa salio zako:
	{vouchers}

	22. Rudi
	00. Ondoka
		 */
		thirdSet: (arg: { vouchers: unknown }) => LocalizedString
		/**
		 * CON Weka PIN ili kuthibitisha chaguo:
	{symbol} {name}
	{contact} {location}
	{description}

	0. Rudi
	00. Ondoka
		 */
		enteringPin: (arg: { contact: unknown, description: unknown, location: unknown, name: unknown, symbol: unknown }) => LocalizedString
		/**
		 * CON Hongera! {symbol} ni Sarafu inayotumika sasa.
	0. Rudi 
	9. Ondoka
		 */
		setSuccess: (arg: { symbol: unknown }) => LocalizedString
		/**
		 * END Kulikuwa na tatizo kwa kuchagua Sarafu. Jaribu tena baadaye.
		 */
		setError: () => LocalizedString
		/**
		 * CON {symbol} {name}
	{contact} {location}
	{description}

	0. Rudi
		 */
		voucherDetails: (arg: { contact: unknown, description: unknown, location: unknown, name: unknown, symbol: unknown }) => LocalizedString
		/**
		 * END PIN yako imefungwa. Kwa usaidizi tafadhali piga simu kwa: {supportPhone}.
		 */
		accountBlocked: (arg: { supportPhone: unknown }) => LocalizedString
		/**
		 * END Asante kwa kutumia huduma ya Sarafu. Kwaheri.
		 */
		exit: () => LocalizedString
	}
}

export type Formatters = {
	currency: (value: unknown) => unknown
	phone: (value: unknown) => unknown
	profileValue: (value: unknown) => unknown
}
