// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Namespaces, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

const localeTranslationLoaders = {
	en: () => import('./en'),
	sw: () => import('./sw'),
}

const localeNamespaceLoaders = {
	en: {
		auth: () => import('./en/auth'),
		balances: () => import('./en/balances'),
		feedback: () => import('./en/feedback'),
		helpers: () => import('./en/helpers'),
		language: () => import('./en/language'),
		main: () => import('./en/main'),
		pin: () => import('./en/pin'),
		profile: () => import('./en/profile'),
		registration: () => import('./en/registration'),
		settings: () => import('./en/settings'),
		socialRecovery: () => import('./en/socialRecovery'),
		statement: () => import('./en/statement'),
		transfer: () => import('./en/transfer'),
		voucher: () => import('./en/voucher')
	},
	sw: {
		auth: () => import('./sw/auth'),
		balances: () => import('./sw/balances'),
		feedback: () => import('./sw/feedback'),
		helpers: () => import('./sw/helpers'),
		language: () => import('./sw/language'),
		main: () => import('./sw/main'),
		pin: () => import('./sw/pin'),
		profile: () => import('./sw/profile'),
		registration: () => import('./sw/registration'),
		settings: () => import('./sw/settings'),
		socialRecovery: () => import('./sw/socialRecovery'),
		statement: () => import('./sw/statement'),
		transfer: () => import('./sw/transfer'),
		voucher: () => import('./sw/voucher')
	}
}

const updateDictionary = (locale: Locales, dictionary: Partial<Translations>): Translations =>
	loadedLocales[locale] = { ...loadedLocales[locale], ...dictionary }

export const importLocaleAsync = async (locale: Locales): Promise<Translations> =>
	(await localeTranslationLoaders[locale]()).default as unknown as Translations

export const loadLocaleAsync = async (locale: Locales): Promise<void> => {
	updateDictionary(locale, await importLocaleAsync(locale))
	loadFormatters(locale)
}

export const loadAllLocalesAsync = (): Promise<void[]> => Promise.all(locales.map(loadLocaleAsync))

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))

export const importNamespaceAsync = async<Namespace extends Namespaces>(locale: Locales, namespace: Namespace) =>
	(await localeNamespaceLoaders[locale][namespace]()).default as unknown as Translations[Namespace]

export const loadNamespaceAsync = async <Namespace extends Namespaces>(locale: Locales, namespace: Namespace): Promise<void> =>
	void updateDictionary(locale, { [namespace]: await importNamespaceAsync(locale, namespace )})
