// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import en from './en'
import sw from './sw'

import en_auth from './en/auth'
import en_balances from './en/balances'
import en_feedback from './en/feedback'
import en_helpers from './en/helpers'
import en_languages from './en/languages'
import en_main from './en/main'
import en_pins from './en/pins'
import en_profile from './en/profile'
import en_registration from './en/registration'
import en_settings from './en/settings'
import en_socialRecovery from './en/socialRecovery'
import en_statement from './en/statement'
import en_transfer from './en/transfer'
import en_voucher from './en/voucher'
import sw_auth from './sw/auth'
import sw_balances from './sw/balances'
import sw_feedback from './sw/feedback'
import sw_helpers from './sw/helpers'
import sw_languages from './sw/languages'
import sw_main from './sw/main'
import sw_pins from './sw/pins'
import sw_profile from './sw/profile'
import sw_registration from './sw/registration'
import sw_settings from './sw/settings'
import sw_socialRecovery from './sw/socialRecovery'
import sw_statement from './sw/statement'
import sw_transfer from './sw/transfer'
import sw_voucher from './sw/voucher'

const localeTranslations = {
	en: {
		...en,
		auth: en_auth,
		balances: en_balances,
		feedback: en_feedback,
		helpers: en_helpers,
		languages: en_languages,
		main: en_main,
		pins: en_pins,
		profile: en_profile,
		registration: en_registration,
		settings: en_settings,
		socialRecovery: en_socialRecovery,
		statement: en_statement,
		transfer: en_transfer,
		voucher: en_voucher
	},
	sw: {
		...sw,
		auth: sw_auth,
		balances: sw_balances,
		feedback: sw_feedback,
		helpers: sw_helpers,
		languages: sw_languages,
		main: sw_main,
		pins: sw_pins,
		profile: sw_profile,
		registration: sw_registration,
		settings: sw_settings,
		socialRecovery: sw_socialRecovery,
		statement: sw_statement,
		transfer: sw_transfer,
		voucher: sw_voucher
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
