// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import en from './en'
import sw from './sw'

import en_feedback from './en/feedback'
import en_sms from './en/sms'
import sw_feedback from './sw/feedback'
import sw_sms from './sw/sms'

const localeTranslations = {
	en: {
		...en,
		feedback: en_feedback,
		sms: en_sms
	},
	sw: {
		...sw,
		feedback: sw_feedback,
		sms: sw_sms
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
