// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'sw'

export type Locales =
	| 'en'
	| 'sw'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​N​D​ ​P​I​N​ ​y​a​k​o​ ​i​m​e​f​u​n​g​w​a​.​ ​K​w​a​ ​u​s​a​i​d​i​z​i​ ​t​a​f​a​d​h​a​l​i​ ​p​i​g​a​ ​s​i​m​u​ ​k​w​a​:​ ​{​0​}​.
	 * @param {unknown} 0
	 */
	accountBlocked: RequiredParams<'0'>
	/**
	 * E​N​D​ ​A​k​a​u​n​t​i​ ​y​a​k​o​ ​y​a​ ​S​a​r​a​f​u​ ​b​a​d​o​ ​i​n​a​t​a​y​a​r​i​s​h​w​a​.​ ​U​t​a​p​o​k​e​a​ ​u​j​u​m​b​e​ ​w​a​ ​S​M​S​ ​a​k​a​u​n​t​i​ ​y​a​k​o​ ​i​k​i​w​a​ ​t​a​y​a​r​i​.
	 */
	accountPendingCreation: string
	/**
	 * E​N​D​ ​A​k​a​u​n​t​i​ ​y​a​k​o​ ​y​a​ ​S​a​r​a​f​u​ ​i​n​a​t​a​y​a​r​i​s​h​w​a​.​ ​U​t​a​p​o​k​e​a​ ​u​j​u​m​b​e​ ​w​a​ ​S​M​S​ ​a​k​a​u​n​t​i​ ​y​a​k​o​ ​i​k​i​w​a​ ​t​a​y​a​r​i​.
	 */
	accountCreationInitiated: string
	/**
	 * C​O​N​ ​S​a​l​i​o​ ​{​0​}​ ​{​1​}​
​1​.​ ​T​u​m​a​
​2​.​S​a​r​a​f​u​ ​y​a​n​g​u​
​3​.​ ​A​k​a​u​n​t​i​ ​y​a​n​g​u​
​4​.​ ​U​s​a​i​d​i​z​i
	 * @param {unknown} 0
	 * @param {unknown} 1
	 */
	mainMenu: RequiredParams<'0' | '1'>
	/**
	 * E​N​D​ ​H​i​t​i​l​a​f​u​ ​t​a​ ​k​i​m​i​t​a​m​b​o​.​ ​T​a​f​a​d​h​a​l​i​ ​j​a​r​i​b​u​ ​t​e​n​a​ ​b​a​a​d​a​y​e​.
	 */
	machineError: string
	/**
	 * C​O​N​ ​C​h​a​g​u​a​ ​l​u​g​h​a​:​
​1​.​ ​K​i​i​n​g​e​r​e​z​a​
​2​.​ ​K​i​s​w​a​h​i​l​i
	 */
	enteringPreferredLanguage: string
}

export type TranslationFunctions = {
	/**
	 * END PIN yako imefungwa. Kwa usaidizi tafadhali piga simu kwa: {0}.
	 */
	accountBlocked: (arg0: unknown) => LocalizedString
	/**
	 * END Akaunti yako ya Sarafu bado inatayarishwa. Utapokea ujumbe wa SMS akaunti yako ikiwa tayari.
	 */
	accountPendingCreation: () => LocalizedString
	/**
	 * END Akaunti yako ya Sarafu inatayarishwa. Utapokea ujumbe wa SMS akaunti yako ikiwa tayari.
	 */
	accountCreationInitiated: () => LocalizedString
	/**
	 * CON Salio {0} {1}
1. Tuma
2.Sarafu yangu
3. Akaunti yangu
4. Usaidizi
	 */
	mainMenu: (arg0: unknown, arg1: unknown) => LocalizedString
	/**
	 * END Hitilafu ta kimitambo. Tafadhali jaribu tena baadaye.
	 */
	machineError: () => LocalizedString
	/**
	 * CON Chagua lugha:
1. Kiingereza
2. Kiswahili
	 */
	enteringPreferredLanguage: () => LocalizedString
}

export type Formatters = {}
